FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY tests/requirements.txt /app/tests/
RUN pip install --no-cache-dir -r /app/tests/requirements.txt

COPY . /app/src/
COPY main.py /app/

CMD ["pytest", "/app/src/tests/"]
